theme: jekyll-theme-cayman
title: TitanObserver
description: Bot Scheduling and Crash Recovery
show_downloads: true
github:
  zip_url: https://github.com/breezko/titanobserver/releases/download/v0.0.3-alpha/build.zip
